// <auto-generated />
namespace DevHub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class adding_fields_in_candidate_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_fields_in_candidate_model));
        
        string IMigrationMetadata.Id
        {
            get { return "202310311039168_adding_fields_in_candidate_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
