// <auto-generated />
namespace DevHub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_more_lenth_for_large_fields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_more_lenth_for_large_fields));
        
        string IMigrationMetadata.Id
        {
            get { return "202312071927310_added_more_lenth_for_large_fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
