// <auto-generated />
namespace DevHub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class nullable_timestamp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nullable_timestamp));
        
        string IMigrationMetadata.Id
        {
            get { return "202310091832218_nullable_timestamp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
