// <auto-generated />
namespace DevHub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_required_and_string_max_length : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_required_and_string_max_length));
        
        string IMigrationMetadata.Id
        {
            get { return "202312071853435_added_required_and_string_max_length"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
