// <auto-generated />
namespace DevHub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class change_data_type_of_phone_field : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_data_type_of_phone_field));
        
        string IMigrationMetadata.Id
        {
            get { return "202312070446485_change_data_type_of_phone_field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
