// <auto-generated />
namespace DevHub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class remove_gender_field_from_job : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_gender_field_from_job));
        
        string IMigrationMetadata.Id
        {
            get { return "202311032000301_remove_gender_field_from_job"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
