// <auto-generated />
namespace DevHub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class states_data : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(states_data));
        
        string IMigrationMetadata.Id
        {
            get { return "202310061010454_states_data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
