// <auto-generated />
namespace DevHub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cascade_true_in_company : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cascade_true_in_company));
        
        string IMigrationMetadata.Id
        {
            get { return "202310120633569_cascade_true_in_company"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
