// <auto-generated />
namespace DevHub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class remove_created_at_from_companyjob_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_created_at_from_companyjob_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202310151119436_remove_created_at_from_companyjob_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
